export const REQUEST_START = "REQUEST_START";

export const LOAD_BLOGLIST_SUCCESSFULLY = "LOAD_BLOGLIST_SUCCESSFULLY";
export const LOAD_BLOGLIST_FAILURE = "LOAD_BLOGLIST_FAILURE";

export const LOAD_BLOG_SUCCESSFULLY = "LOAD_BLOG_SUCCESSFULLY";
export const LOAD_BLOG_FAILURE = "LOAD_BLOG_FAILURE";

export const LOAD_WORKLIST_SUCCESSFULLY = "LOAD_WORKLIST_SUCCESSFULLY";
export const LOAD_WORKLIST_FAILURE = "LOAD_WORKLIST_FAILURE";

export const LOAD_WORK_SUCCESSFULLY = "LOAD_WORK_SUCCESSFULLY";
export const LOAD_WORK_FAILURE = "LOAD_WORK_FAILURE";

export const LOAD_TESTIMONIALS_SUCCESSFULLY = "LOAD_TESTIMONIALS_SUCCESSFULLY";
export const LOAD_TESTIMONIALS_FAILURE = "LOAD_TESTIMONIALS_FAILURE";

export const LOAD_STAFF_SUCCESSFULLY = "LOAD_STAFF_SUCCESSFULLY";
export const LOAD_STAFF_FAILURE = "LOAD_STAFF_FAILURE";

export const LOAD_CLIENTS_SUCCESSFULLY = "LOAD_CLIENTS_SUCCESSFULLY";
export const LOAD_CLIENTS_FAILURE = "LOAD_CLIENTS_FAILURE";

export const POST_CONTACTUS_SUCCESSFULLY = "POST_CONTACTUS_SUCCESSFULLY";
export const POST_CONTACTUS_FAILURE = "POST_CONTACTUS_FAILURE";
